In [3]:
import numpy as np
import pandas as pd
from BuildLinearData import linear_data
from BuildLinearModel import validate_model

### Testing the function on one data set

In [4]:
df1 = pd.read_csv("OrderBook_10.csv")
df2 = pd.read_csv("KlineData_10.csv")
data1 = linear_data(df1, df2)

In [5]:
df = data1.copy()
train, test = np.split(df, [int(0.8*len(df))])

In [6]:
validate_model(train, test, l=5)

Mean squared error: 3136.53
R^2 score: -0.00
Explained variance score: -0.00
Accuracy score: 0.11

We see an r2 score of 0 and an accuracy of only 11 percent. However, I feel like this is due to a really small sample space. If the accuracy uncrease with the size of the datasset that will be a good indication that we are on the right track.

In [7]:
df1 = pd.read_csv("OrderBook_11.csv")
df2 = pd.read_csv("KlineData_11.csv")
data2 = linear_data(df1, df2)

In [10]:
df1 = pd.read_csv("OrderBook_13_1.csv")
df2 = pd.read_csv("KlineData_13_1.csv")
data3 = linear_data(df1, df2)

In [11]:
df1 = pd.read_csv("OrderBook_15_2.csv")
df2 = pd.read_csv("KlineData_15_2.csv")
data4 = linear_data(df1, df2)

In [12]:
df1 = pd.read_csv("OrderBook_16_1.csv")
df2 = pd.read_csv("KlineData_16_1.csv")
data5 = linear_data(df1, df2)

We concatenate all the frames together into one.

In [13]:
frames = [data1, data2, data3, data4, data5]

result = pd.concat(frames)
result

,Price,MidPrice,Spread,MPC,MPB,OIR_(t),VOI_(t),OIR_(t-1),VOI_(t-1),OIR_(t-2),VOI_(t-2),OIR_(t-3),VOI_(t-3),OIR_(t-4),VOI_(t-4),OIR_(t-5),VOI_(t-5)
Time,,,,,,,,,,,,,,,,,
19457 days 12:46:19.187000,28278.7,28278.75,0.10,0.3225,20491.811594,0.333333,-1.601,1.000000,1.946,0.233239,0.023,1.000000,-0.253,0.330986,-0.030,0.332356,-0.243
19457 days 12:46:19.437000,28278.7,28278.75,0.10,0.4000,5335.603774,0.312049,-0.905,0.333333,-1.601,1.000000,1.946,0.233239,0.023,1.000000,-0.253,0.330986,-0.030
19457 days 12:46:22.437000,28278.7,28278.75,0.10,-0.0075,9841.392515,0.121231,2.343,0.049599,-5.032,0.223125,0.059,-1.000000,-1.151,0.260881,0.685,0.229699,6.370
19457 days 12:46:22.687000,28278.8,28278.75,0.10,-0.0075,36741.991342,0.123473,-0.001,0.121231,2.343,0.049599,-5.032,0.223125,0.059,-1.000000,-1.151,0.260881,0.685
19457 days 12:46:22.937000,28278.8,28278.75,0.10,-0.0075,13498.233890,0.124341,0.023,0.123473,-0.001,0.121231,2.343,0.049599,-5.032,0.223125,0.059,-1.000000,-1.151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19464 days 00:22:22.916000,30229.3,30229.25,0.10,0.3750,4024.448871,-0.540459,-0.028,-0.539711,2.256,-0.621636,0.084,1.000000,-0.122,1.000000,-0.013,-0.647253,-2.880
19464 days 00:22:23.166000,30229.3,30233.65,100.00,-4.1475,4024.448871,-1.000000,-3.349,-0.540459,-0.028,-0.539711,2.256,-0.621636,0.084,1.000000,-0.122,1.000000,-0.013
19464 days 00:22:23.416000,30229.2,30229.25,0.10,0.3500,8593.350398,-0.518515,4.171,-1.000000,-3.349,-0.540459,-0.028,-0.539711,2.256,-0.621636,0.084,1.000000,-0.122
19464 days 00:22:23.666000,30229.2,30229.20,0.01,0.5025,229009.090909,1.000000,-0.162,-0.518515,4.171,-1.000000,-3.349,-0.540459,-0.028,-0.539711,2.256,-0.621636,0.084
19464 days 00:22:23.916000,30229.2,30229.20,0.01,0.6025,335880.000000,1.000000,-0.016,1.000000,-0.162,-0.518515,4.171,-1.000000,-3.349,-0.540459,-0.028,-0.539711,2.256

And now we send it through our model.

In [14]:
df = result.copy()
train, test = np.split(df, [int(0.8*len(df))])

In [15]:
validate_model(train, test, l=5)

Mean squared error: 1427.26
R^2 score: -0.00
Explained variance score: -0.00
Accuracy score: 0.26

Bam! We see that our accuracy more than doubled while the errors halved which means our model is workable but we need enough data for that.